name: sperrstunde
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  multi_select_flutter: ^4.0.0
  cached_network_image: ^3.2.0
  provider: ^6.1.2
  http: ^1.3.0
  html: ^0.15.0
  shared_preferences: ^2.0.8
  flutter_svg: ^2.0.17
  path_provider: ^2.0.11
  open_file: ^3.2.1
  intl: ^0.20.2
  photo_view: ^0.15.0
  share_plus: ^10.1.4
  cross_file: ^0.3.4+2
  flutter_cache_manager: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3


  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/Sperrstunde_Logo-Schriftzug_RGB.svg
    - lib/assets/Sperrstunde_Logo-zweizeilig_RGB.png

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/Profilbild_1080x1080.png"

