name: sperrstunde
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  multi_select_flutter: ^4.0.0
  cached_network_image: ^3.2.0
  english_words: ^4.0.0
  provider: ^6.1.2
  http: ^1.3.0
  html: ^0.15.0
  shared_preferences: ^2.0.8
  flutter_svg: ^1.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/Sperrstunde_Logo-Schriftzug_RGB.svg

